source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'
pod 'RETableViewManager'
pod 'NMSSH'
pod 'FontAwesomeKit', '~> 2.1.0'
pod 'GCDWebServer', '~> 3.0'
pod 'GCDWebServer/WebUploader', '~> 3.0'
pod 'Reachability'
pod 'DLSFTPClient'
